version: "3.1"

services:
  app:
    container_name: guestbook
    image: iesgn/guestbook
    restart: always
    ports:
      - "80:5000"

  db:
    container_name: redis
    image: redis
    command: redis-server --appendonly yes
    restart: always
    volumes:
      - ./db:/data
