version: "3.1"
services:
  frontend:
    image: iesgn/temperaturas_frontend
    container_name: temperaturas-fronted
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - backend
      
  backend:
    image: iesgn/temperaturas_backend
    container_name: temperaturas-backend
    restart: always